import { createClient } from "@/lib/supabase/server";
import { getProfileOrRedirect } from "@/lib/get-profile";
import { EmptyState } from "@/components/Loaders";
import StatusBadge from "@/components/StatusBadge";
import { formatDateDMY } from "@/lib/format";
import SchemeRow from "./SchemeRow";

export default async function SchemesOfWorkPage() {
  const profile = await getProfileOrRedirect();
  const supabase = await createClient();
  const canReview = ["principal", "deputy_principal", "hod", "super_admin"].includes(profile.role);

  let query = supabase
    .from("schemes_of_work")
    .select(
      "id, title, status, ai_generated, submitted_at, hod_comments, content, subject:subjects(name), class:classes(name), teacher:staff!schemes_of_work_teacher_id_fkey(first_name, last_name)"
    )
    .order("submitted_at", { ascending: false, nullsFirst: false });

  if (!canReview && profile.staff_id) query = query.eq("teacher_id", profile.staff_id);

  const { data: schemes } = await query;

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-xl font-bold text-gray-900">{canReview ? "Schemes of Work" : "My Schemes of Work"}</h1>
        <p className="text-sm text-gray-500">13-week term schemes generated by teachers, aligned to CBC/8-4-4.</p>
      </div>

      {!schemes || schemes.length === 0 ? (
        <EmptyState title="No schemes of work yet" description="Use the AI Teaching Assistant to generate one." />
      ) : (
        <div className="eduke-table-wrap bg-white rounded-xl border border-gray-100">
          <table>
            <thead>
              <tr className="text-left text-xs text-gray-500 border-b border-gray-100">
                <th className="p-3">Title</th>
                <th className="p-3">Subject</th>
                <th className="p-3">Class</th>
                {canReview && <th className="p-3">Teacher</th>}
                <th className="p-3">AI</th>
                <th className="p-3">Status</th>
                <th className="p-3">Submitted</th>
                <th className="p-3"></th>
              </tr>
            </thead>
            <tbody>
              {schemes.map((sc) => {
                const subject = sc.subject as unknown as { name: string } | null;
                const klass = sc.class as unknown as { name: string } | null;
                const teacher = sc.teacher as unknown as { first_name: string; last_name: string } | null;
                return (
                  <SchemeRow
                    key={sc.id}
                    id={sc.id}
                    title={sc.title}
                    subject={subject?.name ?? "-"}
                    klass={klass?.name ?? "-"}
                    teacher={teacher ? `${teacher.first_name} ${teacher.last_name}` : "-"}
                    aiGenerated={sc.ai_generated}
                    status={sc.status}
                    submitted={formatDateDMY(sc.submitted_at)}
                    content={sc.content ?? ""}
                    hodComments={sc.hod_comments}
                    canReview={canReview}
                  />
                );
              })}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
